kind: pipeline
name: default
type: kubernetes

environment:
  IMAGE_URL: quay.io/ukhomeofficedigital
  IMAGE_REPO: html-pdf-converter

steps:
  - name: install
    image: node:22-slim
    commands:
      - yarn install
    when:
      branch:
        include:
        - master
      event: [ push, pull_request, tag ]

  - name: test
    image: node:22-slim
    commands:
      - yarn test
    when:
      branch:
        include:
        - master
      event: [ push, pull_request, tag ]
    depends_on:
      - install   

  - name: docker_build
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      # wait for docker service to be up before running docker build
      - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
      - docker build --no-cache -t $${IMAGE_REPO}:$${DRONE_TAG} .
    volumes:
      - name: dockersock
        path: /var/run
    when:
      branch:
        include:
        - master
      event: [ push, pull_request, tag ]
    depends_on:
      - test

  # Trivy Security Scannner
  - name: scan-base-image
    pull: always
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
    resources:
      limits:
        cpu: 1000
        memory: 1024Mi
    environment:
      IMAGE_NAME: node:22-slim
      SERVICE_URL: https://acp-trivy-helm.acp-trivy.svc.cluster.local:443 
      TOLERATE: MEDIUM,HIGH,CRITICAL
      FAIL_ON_DETECTION: false
      IGNORE_UNFIXED: true
      ALLOW_CVE_LIST_FILE: cve-exceptions.txt
    volumes:
      - name: dockersock
        path: /var/run
    when:
      branch:
        include:
        - master
      event: [ push, pull_request, tag ]
    depends_on:
      - test

  - name: docker_push
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login -u="ukhomeofficedigital+html_pdf_converter" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag $${IMAGE_REPO}:$${DRONE_TAG} $${IMAGE_URL}/$${IMAGE_REPO}:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/html-pdf-converter:$${DRONE_TAG}
    when:
      branch:
        include:
        - master
      event: [ push, pull_request, tag ]
    depends_on:
      - docker_push

  # Trivy Security Scannner
  - name: scan-packages
    pull: always
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
    resources:
      limits:
        cpu: 1000
        memory: 1024Mi
    environment:
      IMAGE_NAME: html-pdf-converter:$${DRONE_TAG}
      SERVICE_URL: https://acp-trivy-helm.acp-trivy.svc.cluster.local:443 
      TOLERATE: MEDIUM,HIGH,CRITICAL
      FAIL_ON_DETECTION: false
      IGNORE_UNFIXED: true
      ALLOW_CVE_LIST_FILE: cve-exceptions.txt
    volumes:
      - name: dockersock
        path: /var/run
    when:
      branch:
        include:
        - master
      event: [ push, pull_request, tag ]
    depends_on:
      - docker_push

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

volumes:
  - name: dockersock
    temp: {}

...   