kind: pipeline
name: default
type: kubernetes

environment: 
  IMAGE_URL: quay.io/ukhomeofficedigital
  IMAGE_REPO: html-pdf-converter 
steps:
  - name: install
    image: node:22
    commands:
      - npm ci

  - name: test
    image: node:22
    commands:
      - npm test

  - name: audit
    image: node:22
    commands:
      - npm audit --audit-level=high --production

  - name: docker build
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      # wait for docker service to be up before running docker build
      - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
      # - docker build -t html-pdf-converter .
      -  docker build --no-cache -t $${IMAGE_REPO}:$${DRONE_COMMIT_SHA} .

  # - name: scan-image
  #   image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  #   pull: always
  #   environment:
  #     IMAGE_NAME: html-pdf-converter
  #     WHITELIST_FILE: cve-exceptions.txt

  - name: docker push
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login -u="ukhomeofficedigital+html_pdf_converter" -p=$${DOCKER_PASSWORD} quay.io
      #- docker tag html-pdf-converter quay.io/ukhomeofficedigital/html-pdf-converter:$${DRONE_TAG}
      - docker tag $${IMAGE_REPO}:$${DRONE_COMMIT_SHA} $${IMAGE_URL}/$${IMAGE_REPO}:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/html-pdf-converter:$${DRONE_TAG}
    when: 
      branch: master
      event: [ push, pull_request ]
  # Trivy Security Scannner
  - name: scan-packages
    pull: always
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
    resources:
      limits:
        cpu: 1000
        memory: 1024Mi
    environment:
      IMAGE_NAME: html-pdf-converter:${DRONE_COMMIT_SHA}
      TOLERATE: MEDIUM,HIGH,CRITICAL
      FAIL_ON_DETECTION: false
      IGNORE_UNFIXED: true
      ALLOW_CVE_LIST_FILE: hof-services-config/html-pdf-converter/trivy-cve-exceptions.txt
    when:
      branch: master
      event: [ push, pull_request, tag ]
     
  # Trivy Security Scannner
  - name: scan-base-image
    pull: always
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
    resources:
      limits:
        cpu: 1000
        memory: 1024Mi
    environment:
      IMAGE_NAME: node:22.4-alpine3.19@sha256:0d1e8c6ff4362814575daee9c21454dd38984ea29571e9f0eb41f4f26dfa0143
      TOLERATE: MEDIUM,HIGH,CRITICAL
      FAIL_ON_DETECTION: false
      IGNORE_UNFIXED: true
      ALLOW_CVE_LIST_FILE: hof-services-config/html-pdf-converter/trivy-cve-exceptions.txt
    when:
      branch: master
      event: [ push, pull_request, tag ]
      
services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
# - name: anchore-submission-server
#   image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  # pull: always
  # commands:
  #   - /run.sh server

