kind: pipeline
name: default
type: kubernetes

environment:
  IMAGE_URL: quay.io/ukhomeofficedigital
  IMAGE_REPO: html-pdf-converter
# Update the VERSION to a new value for significant changes or releases
# Follow semantic versioning (e.g., v3.0.1 for patches, v3.1.0 for minor changes, v4.0.0 for major changes)
  VERSION: 3.1.0

trigger:
  branch:
    include:
    - master

steps:
  - name: docker_push_version_tag
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
      - docker login -u="ukhomeofficedigital+html_pdf_converter" -p=$${DOCKER_PASSWORD} quay.io
      - docker pull quay.io/ukhomeofficedigital/html-pdf-converter@sha256:42b150c3c441f72ea5d4dc50673fb82e47b1705652bcf62c9b48836e3f70f8ed
      - docker tag quay.io/ukhomeofficedigital/html-pdf-converter@sha256:42b150c3c441f72ea5d4dc50673fb82e47b1705652bcf62c9b48836e3f70f8ed $${IMAGE_URL}/$${IMAGE_REPO}:3.1.0
      - docker push $${IMAGE_URL}/$${IMAGE_REPO}:3.1.0
    when:
      branch:
        include:
        - master
      event: [ push, pull_request, tag ]

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

volumes:
  - name: dockersock
    temp: {}

...   
