kind: pipeline
name: default
type: kubernetes

steps:
  - name: install
    image: node:22-slim
    commands:
      - yarn install

  - name: test
    image: node:22-slim
    commands:
      - yarn test

  - name: docker build
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      # wait for docker service to be up before running docker build
      - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
      - docker build --no-cache -t html-pdf-converter .
    volumes:
      - name: dockersock
        path: /var/run

  # Trivy Security Scannner
  - name: scan-base-image
    pull: always
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
    resources:
      limits:
        cpu: 1000
        memory: 1024Mi
    environment:
      IMAGE_NAME: node:22-slim
      TOLERATE: MEDIUM,HIGH,CRITICAL
      FAIL_ON_DETECTION: false
      IGNORE_UNFIXED: true
      ALLOW_CVE_LIST_FILE: cve-exceptions.txt
    volumes:
      - name: dockersock
        path: /var/run
    when:
      branch:
        include:
        - master
      event: [ push, pull_request, tag ]

  - name: docker push
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login -u="ukhomeofficedigital+html_pdf_converter" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag html-pdf-converter quay.io/ukhomeofficedigital/html-pdf-converter:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/html-pdf-converter:$${DRONE_TAG}
    when:
      event: tag

  # Trivy Security Scannner
  - name: scan-packages
    pull: always
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
    resources:
      limits:
        cpu: 1000
        memory: 1024Mi
    environment:
      IMAGE_NAME: html-pdf-converter:$${DRONE_TAG}
      TOLERATE: MEDIUM,HIGH,CRITICAL
      FAIL_ON_DETECTION: false
      IGNORE_UNFIXED: true
      ALLOW_CVE_LIST_FILE: cve-exceptions.txt
    volumes:
      - name: dockersock
        path: /var/run
    when:
      branch:
        include:
        - master
      event: [ push, pull_request, tag ]

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

volumes:
  - name: dockersock
    temp: {}

...   