apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "html-pdf-converter.fullname" . }}
  labels:
    {{- include "html-pdf-converter.labels" . | nindent 4 }}
    {{- include "html-pdf-converter.platformMandatoryLabels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "html-pdf-converter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}

  template:
    metadata:
      labels:
        {{- include "html-pdf-converter.labels" . | nindent 8 }}
        {{- include "html-pdf-converter.platformMandatoryLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:

        - name: html-pdf-converter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          envFrom:
            - configMapRef:
                name: {{ include "html-pdf-converter.fullname" . }}-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          