{{- $networkPolicy := default (dict) .Values.networkPolicy }}
{{- $namespaceSelector := default (dict) (get $networkPolicy "namespaceSelector") }}
{{- if (default false (get $networkPolicy "enabled")) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: {{ printf "%s-allow-ingress" (include "html-pdf-converter.workloadName" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "html-pdf-converter.labels" . | nindent 4 }}
    {{- include "html-pdf-converter.platformMandatoryLabels" . | nindent 4 }}

spec:
  {{- $nginxProxy := default (dict) .Values.nginxProxy }}
  podSelector:
    matchLabels:
      name: {{ include "html-pdf-converter.workloadName" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
                {{ default "name" (get $namespaceSelector "labelKey") }}: {{ default .Release.Namespace (get $namespaceSelector "labelValue") | quote }}
      ports:
        - port: {{ .Values.env.APP_PORT | default "8080" | int }}
          protocol: TCP
{{- if (default false (get $nginxProxy "enabled")) }}
  - port: {{ default 8443 (get $nginxProxy "containerPort") }}
          protocol: TCP
{{- end }}
{{- end }}