{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: {{ printf "%s-allow-ingress" (include "html-pdf-converter.workloadName" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "html-pdf-converter.labels" . | nindent 4 }}
    {{- include "html-pdf-converter.platformMandatoryLabels" . | nindent 4 }}

spec:
  podSelector:
    matchLabels:
      name: {{ include "html-pdf-converter.workloadName" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{ .Values.networkPolicy.namespaceSelector.labelKey }}: {{ default .Release.Namespace .Values.networkPolicy.namespaceSelector.labelValue | quote }}
      ports:
        - port: {{ .Values.env.APP_PORT | default "8080" | int }}
          protocol: TCP
{{- if .Values.nginxProxy.enabled }}
        - port: {{ default 8443 .Values.nginxProxy.containerPort }}
          protocol: TCP
{{- end }}
{{- end }}