apiVersion: v1
kind: Service

metadata:
  name: {{ include "html-pdf-converter.fullname" . }}
  labels:
    {{- include "html-pdf-converter.labels" . | nindent 4 }}
    {{- include "html-pdf-converter.platformMandatoryLabels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app.kubernetes.io/name: {{ include "html-pdf-converter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP