apiVersion: v1
kind: Service

metadata:
  name: {{ include "html-pdf-converter.deploymentName" . }}
  labels:
    {{- include "html-pdf-converter.serviceLabels" . | nindent 4 }}
    {{- include "html-pdf-converter.platformMandatoryLabels" . | nindent 4 }}

spec:
  type: {{ default "ClusterIP" .Values.service.type }}

  selector:
    {{- include "html-pdf-converter.serviceSelector" . | nindent 4 }}

  ports:
    - name: http
      port: {{ default 10080 .Values.service.port }}
      targetPort: nginx-http
      protocol: TCP
    - name: https
      port: {{ default 10443 .Values.service.httpsPort }}
      targetPort: nginx-https
      protocol: TCP